### PR TITLE
Miscellaneous

### PR DESCRIPTION
**Pull request by Calrama**
Just some more API methods.

### CODE REVIEW

**Comment by filcuc** [comment]
fine thank you :smile:

**Comment by Calrama** [comment]
> fine thank you

No problem, just happy that I'm finally getting used to git cherry-picking ^^°



> btw i think this could be also an improvement when passing the string instead of the current solution used in the DOtherSide.

Tell me if I'm wrong, but the stack frame you're allocating that on is gone the moment the C function returns and the memory won't be valid anymore AFAICT.

> Infact right now we are making useless heap allocations plus the need on the other side to call the dos_chararray_delete

Agreed on that they're annoying, but they are useful (as I see them) to clearly indicate memory ownership. Also, allocating small bits of memory like this should be so insanely fast (on any decent OS I know of) that I personally can live with that overhead to get the clear memory model.

**Comment by Calrama** [comment]
Sorry for double-post: But github claims that this was closed without merging?

**Comment by filcuc** [comment]
sorry my fault, i didn't merge it (only closed it)
However after evaluating it a little i've some doubts:
1) From dos_qqmlapplicationengine_rootObjects you're returning an array of QObjects*
On the other side (D/Nim) this QObjects* are different from the one we create with dos_qobject_create.
The reason is that supporting the addition and removal of slots and signals we must derive from DynamicQObject that is a subclass of QObject.
So it's wrong to return return an array of QObjects from the QQApplicationEngine::rootObjects() functions. One solution is to make explicit on the binding language that what we create are not QObjects but DynamicQObjects. However this is ugly! i didn't want that.
I've to think a little about how to make it work correctly and nicely.

**Comment by Calrama** [comment]
> On the other side (D/Nim) this QObjects* are different from the one we create with dos_qobject_create. The reason is that supporting the addition and removal of slots and signals we must derive from DynamicQObject that is a subclass of QObject. So it's wrong to return an array of QObjects from the QQApplicationEngine::rootObjects() functions.

Those objects are  instantiated by QtQuick internally as a result of loading from QML, not by DOtherSide. AFAIK they are thus not instances of DynamicQObject. I had no intention of allowing addition/removal of slots and signals for them, as their slots and signals are defined in QML.

> One solution is to make explicit on the binding language that what we create are not QObjects but DynamicQObjects. However this is ugly! i didn't want that.
> I've to think a little about how to make it work correctly and nicely.

Ok, I'm not sure I really get the issue here, but I'm not currently using it anyway. I added this while I was debugging the receiving signal bits (I had a really stupid bug there and this allowed me to find it).

**Comment by filcuc** [comment]
ok i checked the QObject interface in D and basically everything is protected and so nothing is callable from those QObjects returned from QQmlApplicationEngine::rootObjects. So we are safe from a user calling emit or register signals etc.

**Pull request merged**
